### PR TITLE
Add support for custom git tags

### LINKED ISSUE #16: Specify version
Love this project!  I've been experimenting with ways for https://github.com/aws-amplify/amplify-js/ to publish PR-previews (where each commit of a PR gets published artifacts so customers can validate PRs _before_ merging), and I think this project could be perfect.

For a PR, I would like customize the following:
https://github.com/ramasilveyra/gitpkg/blob/9c02f228fd8f6a4f31d35631a9a2f95a76ca7adb/src/tasks/Publish/get-git-tag-name.js#L3-L5

What's the best way could be handled?  I'm happy to submit a PR so we could support some convention like `1.2.3-PR456-abc789` that would help us prune releases after they're respective PRs have been merged...

### PR DESCRIPTION
**Pull request by thejsn**
This adds support for custom git tags through an **optional** `gitpkg.config.js` file.
Possibly fixes #16 too

### CODE REVIEW

**Comment by ramasilveyra** [comment]
This is looking great! I think that I don't mind dropping support for node v6 and releasing this as a breaking change. I will take a deep look during this week. Thanks!

**Comment by thejsn** [comment]
@ramasilveyra  Thanks for having a look! I was a bit confused why the tests failed though. It looks like it's failing on the `async` tests but that has been there all the time, no? 
Anyway, this is my first PR so please let me know if i've missed anything that needs to be fixed.

**Comment by ramasilveyra** [comment]
merging, I will fix ci with https://github.com/ramasilveyra/gitpkg/pull/18 by dropping support for old node versions

**Comment by ramasilveyra** [comment]
thanks for this, it looks great! Sorry for my delay

**Comment by ramasilveyra** [comment]
Published in [v1.0.0-beta.2](https://github.com/ramasilveyra/gitpkg/blob/v1.0.0-beta.2/CHANGELOG.md#100-beta2-2020-03-30).

**Pull request merged**
